### ISSUE TITLE
我在k210开发板上启动xv6-k210时遇到了一个中断bug，请问如何解决呢？

### ISSUE THREAD

**Issue by mmyyy22** [HUST-OS/xv6-k210#13]
![QQ图片20210502162957](https://user-images.githubusercontent.com/67685687/116807120-e494c880-ab63-11eb-943b-f63d9a89bdb9.jpg)

**Comment by AtomHeartCoder** [comment]
从mepc来看，这个异常应该是发生在SBI中，请问您对代码做了哪些修改呢？

**Comment by mmyyy22** [comment]
并没有对代码进行修改，可能是操作问题吧，现在能够正常运行了，没有再遇到相同问题。
