### ISSUE TITLE
改进时钟中断处理时遇到的问题

### ISSUE THREAD

**Issue by sunshine-lcc** [HUST-OS/xv6-k210#21]
为什么在时钟中断处理时，访问当前进程里面的属性时，
![image](https://user-images.githubusercontent.com/29215152/117995938-4e874c00-b374-11eb-9083-0f9dec8ca9b3.png)
会引发未知的内核态软中断错误呢？
![image](https://user-images.githubusercontent.com/29215152/117996171-82627180-b374-11eb-927b-ac7479b17b28.png)

**Comment by Luchangcheng2333** [comment]
> 为什么在时钟中断处理时，访问当前进程里面的属性时，
> ![image](https://user-images.githubusercontent.com/29215152/117995938-4e874c00-b374-11eb-9083-0f9dec8ca9b3.png)
> 会引发未知的内核态软中断错误呢？
> ![image](https://user-images.githubusercontent.com/29215152/117996171-82627180-b374-11eb-927b-ac7479b17b28.png)

在访问当前进程的pid等属性时也遇到这个问题
