### ISSUE TITLE
在已安装PySerial的前提下，make run仍提示需要安装PySerial（运行在K210开发板上）

### ISSUE THREAD

**Issue by R1pTheJacker** [HUST-OS/xv6-k210#22]
![6P_J4P 77K)~7`7C~5M6~ V](https://user-images.githubusercontent.com/61656773/118361515-6a7e2e00-b5be-11eb-87e9-742590e19b1c.png)

**Comment by SKTT1Ryze** [comment]
试一下 :  
```bash
sudo pip3 install pyserial
```
因为 root 用户和普通用户的 py 库是独立的

**Comment by R1pTheJacker** [comment]
> 试一下 :
> 
> ```shell
> sudo pip3 install pyserial
> ```
> 
> 因为 root 用户和普通用户的 py 库是独立的

谢谢，已解决
