### ISSUE TITLE
修改物理内存最大值引起的问题

### ISSUE THREAD

**Issue by sunshine-lcc** [HUST-OS/xv6-k210#31]
请教下为什么物理内存的最大值PHYSTOP改得比较大之后，会卡死在物理页帧分配函数kinit这里呢？QEMU配置给的内存已经足够大了也出现这个问题
![2021-06-22_08-33-18](https://user-images.githubusercontent.com/29215152/122864624-8a400900-d357-11eb-83f5-ca1af4678bb3.png)

**Comment by retrhelo** [comment]
> 为什么物理内存的最大值PHYSTOP改得比较大之后，会卡死在物理页帧分配kinit这里呢？
> ![2021-06-22_08-33-18](https://user-images.githubusercontent.com/29215152/122864624-8a400900-d357-11eb-83f5-ca1af4678bb3.png)
> 
> 

可能是访问异常导致的，从图上来看，似乎是假定在内核空间之后还有128MB的空间，而实际上显然是没有
这么大的。试图访问一段不存在的内存空间会导致异常。我想可能是这个原因导致的。如果可以话不妨检查
一下内核的panic信息？如果内核没有打印任何信息的话，那么问题只可能会更为复杂。
