### ISSUE TITLE
QEMU下初始化PLIC会panic

### ISSUE THREAD

**Issue by chinoll** [HUST-OS/xv6-k210#34]
![a](https://user-images.githubusercontent.com/22575232/128381795-d21087a1-2dd9-4b78-8a99-bc7488d9731e.jpg)
在qemu5.1.0和6.0.0下均出现这个问题

**Comment by retrhelo** [comment]
这个是新版本的RustSBI设置PMP（物理内存保护）导致的问题。把RustSBI里面相关的代码去掉就行。但是xv6-k210为了适应k210平台，对RustSBI上的代码做了一些魔改。所以现在新版本的RustSBI没有办法直接用在xv6-k210上面。
