### ISSUE TITLE
tf卡启动失败

### ISSUE THREAD

**Issue by t812206236** [HUST-OS/xv6-k210#35]
启动失败，提示不是fat32
然后我打印了tf卡的前512
![](https://z3.ax1x.com/2021/10/11/5Zg5L9.png)
![](https://z3.ax1x.com/2021/10/11/5ZgTd1.png)
可以看到后面有0x55 0xaa，但是前面的内容好像完全错了，我以为是我tf卡格式化有问题，然后我导出了tf卡前512
![](https://z3.ax1x.com/2021/10/11/5ZgoZR.png)
发现是对的，没有问题，有fat32标识，然后我以为是硬件pin脚不一致导致的，我对照了一下官方的，是这样的
![](https://z3.ax1x.com/2021/10/11/5Zg4sJ.png)
但是这个工程中初始化是写在fpioa.c，是这样的
![](https://z3.ax1x.com/2021/10/11/5ZghM4.png)
多了一个32号pin脚不明白是为什么（完全不懂硬件）
![](https://z3.ax1x.com/2021/10/11/5ZgWzF.png)
而且在初始化的时候片选是3，但是在这里片选却是7
但是我改成我想的样子后，连本来能读取的都读取不了，所以很困惑到底发生了什么，希望能帮忙解惑！

**Comment by t812206236** [comment]
可以了，是我格式化的问题，好像使用图形化界面的工具格式化，都是带有分区的，必须使用指令mkfs.fat -F32 /dev/sdX。另外能给我讲讲为什么硬件的初始化是这样的吗？

**Comment by retrhelo** [comment]
关于这个问题可以看一下我们贴在Issue页面的[Issue#14](https://github.com/HUST-OS/xv6-k210/issues/14)，问题差不多是类似的。使用`mkfs.fat -F32 /dev/sdX`的主要目的是不留下分区表，因为目前xv6-k210还不支持分区表，其会默认FAT32文件系统从SD卡的零号扇区开始。
