### ISSUE TITLE
qemu模拟器

### ISSUE THREAD

**Issue by suxiao111** [HUST-OS/xv6-k210#37]
运行在qemu-system-riscv64上，模拟器是基于k210的板子吗

**Comment by retrhelo** [comment]
QEMU模拟和k210是有区别的。一些主要的区别在于

- 内存布局的不同
- 外设驱动不同
- k210的指令集实现较老

在代码中你可以看见很多地方使用了条件编译，这些代码就是QEMU和k210的不同之处。

**Comment by suxiao111** [comment]
qemu-system-riscv64的参数中， -machine设置的是 virt，-device设置的是 virtio-blk-device，模拟器和基于k210的板子没什么关系吗？

**Comment by suxiao111** [comment]
qemu-system-riscv64的参数中， -machine设置的是 virt，-device设置的是 virtio-blk-device，模拟器和基于k210的板子没什么关系吗？

**Comment by retrhelo** [comment]
我记得QEMU是没有提供k210的仿真模拟的。

**Comment by suxiao111** [comment]
好的，感谢
