### ISSUE TITLE
用opensbi启动出错

### ISSUE THREAD

**Issue by zbtrs** [HUST-OS/xv6-k210#38]
在make build platform=qemu和make fs后，使用命令：qemu-system-riscv64 -machine virt -bios default -m 128M -nographic -kernel target/kernel
会进入到xv6-qemu，但是提示panic: could not find virtio disk
backtrace:
0x000000008020017c
0x0000000080206f90
0x0000000080204fb6
0x0000000080200aa0
这个该怎么办呢？

**Comment by SKTT1Ryze** [comment]
我看这个issue已经关掉了，问题已经解决了么？这个报错看起来是因为qemu没有正确配置`virtio disk`？

**Comment by zbtrs** [comment]
是的，已经解决了
