### ISSUE TITLE
无法在qemu7.0.0上运行

### ISSUE THREAD

**Issue by ckyanos** [HUST-OS/xv6-k210#40]
<img width="735" alt="屏幕截图 2023-04-11 180737" src="https://user-images.githubusercontent.com/48557422/231128972-2cf21900-d747-47c3-ba2d-f7f24c0eb8b1.png">

**Comment by retrhelo** [comment]
RustSBI提供了mepc和对应的指令，可以先根据报错信息做进一步调试。
