### ISSUE TITLE
报错：Some ROM regions are overlapping

### ISSUE THREAD

**Issue by qiulin13145** [HUST-OS/xv6-k210#41]
QEMU 版本7.0.0 ，在执行make run platform=qemu 时报错：
![image](https://github.com/HUST-OS/xv6-k210/assets/144438757/5821193f-8b33-481b-9419-853334f9b0e9)

据我测试，这个错误在QEMU 6.2.0版本和7.0.0版本似乎都有出现。
请问该如何解决呢！感谢！

**Comment by SKTT1Ryze** [comment]
好像是`sbi`固件写入qemu ROM的时候越界了，朋友可以更换qemu版本试试。因为这个项目的开发时间是在两年前了，因此我也忘了当时是用的qemu哪个版本了。可以试试`6.1`版本？

**Comment by retrhelo** [comment]
这个问题是由于QEMU的地址空间冲突导致的。一个比较简单的解决方法是修改Makefile中`QEMUOPT`下的`-m`选项来增大模拟时的内存空间大小。改成`-m 32M`应该就可以解决问题了。

当然，这个解决方法比较直白，我觉得应该还有更好的方法。

**Comment by qiulin13145** [comment]
问题解决了！非常感谢两位大佬百忙之中抽空解答我的困惑！
