### ISSUE TITLE
如何修改之前存在的系统调用号

### ISSUE THREAD

**Issue by Luchangcheng2333** [HUST-OS/xv6-k210#7]
如图，我修改了之前存在的系统调用号
![2021-04-29_15-17-04](https://user-images.githubusercontent.com/29215152/116514793-14429700-a8fe-11eb-9888-876293af548f.png)
但是，为什么运行的时候系统调用好不会变呢？应该怎么修改之前的系统调用号呢？
![2021-04-29_15-19-18](https://user-images.githubusercontent.com/29215152/116514973-47852600-a8fe-11eb-82b5-4178c6c6ac5b.png)

**Comment by retrhelo** [comment]
On Thu, 29 Apr 2021 00:19:48 -0700
Luchangcheng2333 ***@***.***> wrote:

> 如图，我修改了之前存在的系统调用号
> ![2021-04-29_15-17-04](https://user-images.githubusercontent.com/29215152/116514793-14429700-a8fe-11eb-9888-876293af548f.png)
> 但是，为什么运行的时候系统调用好不会变呢？应该怎么修改之前的系统调用号呢？
> ![2021-04-29_15-19-18](https://user-images.githubusercontent.com/29215152/116514973-47852600-a8fe-11eb-82b5-4178c6c6ac5b.png)
> 
> 

`initcode`程序的代码是通过十六进制数据的形式硬编码进xv6-k210的代码中的。可以在kernel/proc.c中
找到名为`initcode`的uchar数组，即为`initcode`的十六进制编码。而`initcode`本身的汇编代码保存
在xv6-user/initcode.S中。  

在`initcode`中，调用了SYS_exec这样一个系统调用。在修改了系统调用号之后，需要将initcode.S所生成的
目标文件initcode.o的十六进制编码重新写到kernel/proc.c中的`initcode`数组。
